# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MiniProject(object):
    def setupUi(self, MiniProject):
        MiniProject.setObjectName("MiniProject")
        MiniProject.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MiniProject)
        self.centralwidget.setObjectName("centralwidget")
        self.button1 = QtWidgets.QPushButton(self.centralwidget)
        self.button1.setGeometry(QtCore.QRect(0, 0, 171, 41))
        self.button1.setObjectName("button1")
        self.button2 = QtWidgets.QPushButton(self.centralwidget)
        self.button2.setGeometry(QtCore.QRect(0, 40, 171, 41))
        self.button2.setObjectName("button2")
        self.button3 = QtWidgets.QPushButton(self.centralwidget)
        self.button3.setGeometry(QtCore.QRect(0, 80, 171, 41))
        self.button3.setObjectName("button3")
        self.button4 = QtWidgets.QPushButton(self.centralwidget)
        self.button4.setGeometry(QtCore.QRect(0, 120, 171, 41))
        self.button4.setObjectName("button4")
        self.button5 = QtWidgets.QPushButton(self.centralwidget)
        self.button5.setGeometry(QtCore.QRect(0, 160, 171, 41))
        self.button5.setObjectName("button5")
        self.button6 = QtWidgets.QPushButton(self.centralwidget)
        self.button6.setGeometry(QtCore.QRect(0, 200, 171, 41))
        self.button6.setObjectName("button6")
        self.button7 = QtWidgets.QPushButton(self.centralwidget)
        self.button7.setGeometry(QtCore.QRect(0, 240, 171, 41))
        self.button7.setObjectName("button7")
        self.button8 = QtWidgets.QPushButton(self.centralwidget)
        self.button8.setGeometry(QtCore.QRect(0, 280, 171, 41))
        self.button8.setObjectName("button8")
        self.button9 = QtWidgets.QPushButton(self.centralwidget)
        self.button9.setGeometry(QtCore.QRect(0, 320, 171, 41))
        self.button9.setObjectName("button9")
        self.button10 = QtWidgets.QPushButton(self.centralwidget)
        self.button10.setGeometry(QtCore.QRect(0, 360, 171, 41))
        self.button10.setObjectName("button10")
        self.runbutton = QtWidgets.QPushButton(self.centralwidget)
        self.runbutton.setGeometry(QtCore.QRect(0, 450, 241, 101))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.runbutton.setFont(font)
        self.runbutton.setObjectName("runbutton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(190, 0, 591, 31))
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(190, 40, 591, 31))
        self.label_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(280, 450, 211, 101))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(530, 450, 221, 101))
        self.pushButton_2.setObjectName("pushButton_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(190, 81, 591, 321))
        self.textBrowser.setObjectName("textBrowser")
        MiniProject.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MiniProject)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        MiniProject.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MiniProject)
        self.statusbar.setObjectName("statusbar")
        MiniProject.setStatusBar(self.statusbar)

        self.retranslateUi(MiniProject)
        QtCore.QMetaObject.connectSlotsByName(MiniProject)

    def retranslateUi(self, MiniProject):
        _translate = QtCore.QCoreApplication.translate
        MiniProject.setWindowTitle(_translate("MiniProject", "MainWindow"))
        self.button1.setText(_translate("MiniProject", "PushButton"))
        self.button2.setText(_translate("MiniProject", "PushButton"))
        self.button3.setText(_translate("MiniProject", "PushButton"))
        self.button4.setText(_translate("MiniProject", "PushButton"))
        self.button5.setText(_translate("MiniProject", "PushButton"))
        self.button6.setText(_translate("MiniProject", "PushButton"))
        self.button7.setText(_translate("MiniProject", "PushButton"))
        self.button8.setText(_translate("MiniProject", "PushButton"))
        self.button9.setText(_translate("MiniProject", "PushButton"))
        self.button10.setText(_translate("MiniProject", "PushButton"))
        self.runbutton.setText(_translate("MiniProject", "RUN"))
        self.label.setText(_translate("MiniProject", "TextLabel"))
        self.label_2.setText(_translate("MiniProject", "TextLabel"))
        self.pushButton.setText(_translate("MiniProject", "PushButton"))
        self.pushButton_2.setText(_translate("MiniProject", "PushButton"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MiniProject = QtWidgets.QMainWindow()
    ui = Ui_MiniProject()
    ui.setupUi(MiniProject)
    MiniProject.show()
    sys.exit(app.exec_())
